language: node_js
node_js:
- lts/*
cache: npm
script:
  - cd frontend
  - npm install
  - npm run build
  - cd dist
  - cd ../../backend/
  - mv docker-compose.yml dockerfile requirements.txt server.py ../frontend/dist
  - cd ../frontend
  - npm run deploy
