FROM python:3.8 as caerme
COPY requirements.txt /
RUN apt-get install libxml2-dev libxslt-dev
RUN pip install -r /requirements.txt

COPY static/ /static/
COPY templates/ /templates/
COPY config.json /config.json
COPY Server.py /Server.py

WORKDIR /
